### ISSUE TITLE
Sprint 15: Core Data

### ISSUE THREAD

**Issue by andreichenchik** [maxim-papier/TrackerApp#11]
Завершите работу с элементами дизайна для экрана добавления нового трекера:

- [x] коллекцию для выбора эмоджи (помните, что выбрать можно только одну эмоджи; выделяем её серым фоном);
- [x] коллекцию для выбора цвета (цвет тоже можно выбрать только один; выделяем его тонким обрамлением);
- [x] кнопку для перехода к экрану с категориями (или ничего, если мы пока не будем никуда переходить);
- [x] кнопку для перехода на экран с расписанием (отображаем её, если пользователь ранее указывал, что хочет добавить «Привычку», а не «Нерегулярное событие»).

Вам нужно сдать проект, в котором:
- [x] завершены работы над экраном добавления новой привычки;
- [x] реализован слой работы с базой данных с использованием абстракций.

Убедитесь, что:
- [x] Завершены работы над экраном добавления новой привычки. На этот экран добавлены:  
    - [x] коллекция для выбора эмоджи (выбрать можно только одну эмоджи; выделяем её серым фоном);
    - [x] коллекция для выбора цвета (цвет можно выбрать только один; выделяем его тонким обрамлением);
    - [x] кнопка для перехода к экрану с категориями (или ничего, если мы пока не будем никуда переходить);
    - [x] кнопка для перехода на экран с расписанием (отображаем её, если пользователь ранее указывал, что хочет добавить «Привычку», а не «Нерегулярное событие»).
        
- [x] Реализован слой работы с базой данных с использованием абстракций:
    - [x] добавлены классы `TrackerStore`, `TrackerCategoryStore`, `TrackerRecordStore` для абстрагирования Core Data;
    - [x] добавлены Entity для хранения `Tracker`, `TrackerCategory`, `TrackerRecord`;
    - [x] у каждой Entity имеется префикс, чётко обозначющий, что она используется для хранения в Core Data (например, `TrackerCoreData`);
    - [x] в модели (файл с расширением `*.xcdatamodeld`) указаны взаимосвязи между Entity;
    - [x] для своевременного получения обновлений от Core Data используется `NSFetchedResultsController`;
    - [x] можно создавать привычки и нерегулярные события и после перезапуска информация отображается; иначе говоря - слой хранения данных (на базе Core Data) выполняет свои задачи;
    - [x] нигде, кроме `Store.swift`\-файлов, нет строчки `import CoreData`; иначе говоря - приложение надежно абстрагировано от Core Data.

**Comment by maxim-papier** [comment]
done
